#!/usr/bin/env bash
# Transfers a file from our client to a server
#
# Check for correct number of arguments
if [ $# -ne 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

# Construct the scp command
scp_command="scp -o StrictHostKeyChecking=no $file_path $username@$server_ip:~/"

# Execute the scp command
eval "$scp_command"
