#!/usr/bin/env bash
# backup and compress my databases

# variables
day=$(date +"%d")
month=$(date +"%m")
year=$(date +"%Y")
file_name="$day-$month-$year.tar.gz"

mysqldump -u root -p"$1" tyrell_corp > backup.sql
tar -czvf "$file_name" backup.sql
