#!/bin/bash

# Install UFW
sudo apt install -y ufw

# Enable UFW
sudo ufw enable

# Deny all incoming traffic
sudo ufw default deny incoming

# Allow specific ports
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
